language: python
dist: xenial
cache: pip
install: true

addons:
  postgresql: "10"

matrix:
  include:
  - python: "3.7"
    env: RL_TRAVIS_TEST=test PY_EXE=python3.7
  - python: "3.7"
    env: RL_TRAVIS_TEST=test_expensive PY_EXE=python3.7
  - python: "3.7"
    env: RL_TRAVIS_TEST=test_postgres PY_EXE=python3.7

  - python: "3.7"
    env: RL_TRAVIS_TEST=cmdline PY_EXE=python3.7
  - python: "3.7"
    env: RL_TRAVIS_TEST=flake8 PY_EXE=python3.7
  - python: "3.7"
    env: RL_TRAVIS_TEST=mypy PY_EXE=python3.7
script:
  - bash ./run-travis-ci.sh
